<?php

return  [

    "Andhra Pradesh" => [
        "Allurisitharamaraju",
        "Ananthapuramu",
        "Annamayya",
        "Anakapalli",
        "Baptla",
        "Chittoor",
        "East Godavari",
        "Eluru",
        "Guntur",
        "Kakinada",
        "Konaseema",
        "Krishna",
        "Kurnool",
        "Nandyal",
        "N.T.R",
        "Palnadu",
        "Parvathipurammanyam",
        "Prakasam",
        "Srisathyasai",
        "SPS Nellore",
        "Srikakulam",
        "Tirupati",
        "Visakhapatnam",
        "Vizianagaram",
        "West Godavari",
        "YSR Kadapa"
    ],
    "Arunachal Pradesh" => [
        "Anjaw",
        "Changlang",
        "Dibang Valley",
        "East Kameng",
        "East Siang",
        "Itanagar",
        "Kra Daadi",
        "Kurung Kumey",
        "Lohit",
        "Longding",
        "Lower Dibang Valley",
        "Lower Subansiri",
        "Namsai",
        "Papumpare",
        "Shiyomi",
        "Siang",
        "Tawang",
        "Tirap",
        "Upper Siang",
        "Upper Subansiri",
        "West Kameng",
        "West Siang"
    ],
    "Assam" =>  [
        "Baksa",
        "Barpeta",
        "Bongaigaon",
        "Cachar",
        "Charaideo",
        "Chirang",
        "Darrang",
        "Dhemaji",
        "Dhubri",
        "Dibrugarh",
        "Dima Hasao",
        "Goalpara",
        "Golaghat",
        "Hailakandi",
        "Jorhat",
        "Kamrup Metropolitan",
        "Kamrup",
        "Karbi Anglong",
        "Karimganj",
        "Kokrajhar",
        "Lakhimpur",
        "Majuli",
        "Morigaon",
        "Nagaon",
        "Sivasagar",
        "Sonitpur",
        "South Salmara-Mankachar",
        "Tinsukia",
        "Udalguri",
        "West Karbi Anglong"
    ],
    "Bihar" =>  [
        "Araria",
        "Arwal",
        "Aurangabad",
        "Banka",
        "Begusarai",
        "Bhagalpur",
        "Bhojpur",
        "Buxar",
        "Darbhanga",
        "East Champaran",
        "Gaya",
        "Gopalganj",
        "Jamui",
        "Jehanabad",
        "Kaimur",
        "Katihar",
        "Khagaria",
        "Kishanganj",
        "Lakhisarai",
        "Madhepura",
        "Madhubani",
        "Munger",
        "Muzaffarpur",
        "Nalanda",
        "Nawada",
        "Patna",
        "Purnea",
        "Rohtas",
        "Saharsa",
        "Samastipur",
        "Saran",
        "Sheikhpura",
        "Sheohar",
        "Sitamarhi",
        "Siwan",
        "Supaul",
        "Vaishali",
        "West Champaran"
    ],
    "Chhattisgarh" =>  [
        "Balod",
        "Balodabazar Bhatapara",
        "Balrampur",
        "Bastar",
        "Bemetara",
        "Bijapur",
        "Bilaspur",
        "Dantewada",
        "Dhamtari",
        "Durg",
        "Gariaband",
        "Gaurela Pendra Marwahi",
        "Jangir Champa",
        "Jashpur",
        "Kanker",
        "Kawardha",
        "Kondagaon",
        "Korba",
        "Korea",
        "Mahasamund",
        "Mungeli",
        "Narayanpur",
        "Raigarh",
        "Raipur",
        "Rajnandgaon",
        "Sukma",
        "Surajpur",
        "Surguja"
    ],
    "Goa" =>  ["North Goa", "South Goa"],
    "Gujarat" =>  [
        "Ahmedabad",
        "Amreli",
        "Anand",
        "Arvalli",
        "Banaskantha",
        "Bharuch",
        "Bhavnagar",
        "Botad",
        "Chhotaudepur",
        "Dahod",
        "Devbhumi Dwarka",
        "Gandhinagar",
        "Gir Somnath",
        "Jamnagar",
        "Junagadh",
        "Kutch",
        "Kheda",
        "Mahesana",
        "Mahisagar",
        "Morbi",
        "Narmada",
        "Navsari",
        "Panchmahals",
        "Patan",
        "Porbandar",
        "Rajkot",
        "Sabarkantha",
        "Surat",
        "Surendranagar",
        "Tapi",
        "Dang",
        "Vadodara",
        "Valsad"
    ],
    "Haryana" =>  [
        "Ambala",
        "Bhiwani",
        "Charkhi Dadri",
        "Faridabad",
        "Fathehabad",
        "Gurugram",
        "Hisar",
        "Jhajjar",
        "Jind",
        "Kaithal",
        "Karnal",
        "Kurukshetra",
        "Mahendragarh",
        "Nuh",
        "Palwal",
        "Panchkula",
        "Panipat",
        "Rewari",
        "Rohtak",
        "Sirsa",
        "Sonipat",
        "Yamunanagar"
    ],
    "Himachal Pradesh" =>  [
        "Bilaspur",
        "Chamba",
        "Hamirpur",
        "Kangra",
        "Kinnaur",
        "Kullu",
        "Lahaul and Spiti",
        "Mandi",
        "Shimla",
        "Sirmapur",
        "Solan",
        "Una"
    ],
    "Jharkhand" =>  [
        "Bokaro",
        "Chaibasa",
        "Chatra",
        "Deoghar",
        "Dhanbad",
        "Dumka",
        "Garhwa",
        "Giridih",
        "Godda",
        "Gumla",
        "Hazaribagh",
        "Jamshedpur",
        "Jamtara",
        "Khunti",
        "Koderma",
        "Latehar",
        "Lohardaga",
        "Pakur",
        "Palamu",
        "Ramgarh",
        "Ranchi",
        "Sahibganj",
        "Seraikela",
        "Simdega"
    ],

    "Karnataka" =>  [
        "Bidar",
        "Kalaburagi",
        "Vijaypura",
        "Yadagiri",
        "Belagavi",
        "Bagalkot",
        "Raichur",
        "Uttar Kannada",
        "Dharwad",
        "Gadag",
        "Koppal",
        "Ballari",
        "Vijayanagar",
        "Haveri",
        "Davangere",
        "Shivamogga",
        "Udupi",
        "Chikkamagaluru",
        "Chitradurga",
        "Dakshin Kannada",
        "Kodagu",
        "Hassan",
        "Tumakuru",
        "Mysuru",
        "Mandya",
        "Chamrajnagar",
        "Ramanagara",
        "Bengluru",
        "Bengaluru Rural",
        "Kolar",
        "Chikkaballapura"
    ],

    "Kerala" =>  [
        "Alappuzha",
        "Ernakulam",
        "Idukki",
        "Kannur",
        "Kasaragod",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Mallapuram",
        "Palakkad",
        "Pathanamthitta",
        "Thrissur",
        "Trivandrum",
        "Wayanad"
    ],
    "Madhya Pradesh" =>  [
        "Agar Malwa",
        "Alirajpur",
        "Anuppur",
        "Ashokanagar",
        "Balaghat",
        "Barwani",
        "Betul",
        "Bhind",
        "Bhopal",
        "Burhanpur",
        "Chhatarpur",
        "Chhindwara",
        "Damoh",
        "Datia",
        "Dewas",
        "Dhar",
        "Dindori",
        "Guna",
        "Gwalior",
        "Harda",
        "Indore",
        "Jabalpur",
        "Jhabua",
        "Katni",
        "Khandwa",
        "Khargone",
        "Mandla",
        "Mandsaur",
        "Mauganj",
        "Morena",
        "Narmadapurm",
        "Narsinghpur",
        "Neemuch",
        "Niwari",
        "Panna",
        "Raisen",
        "Rajgarh",
        "Ratlam",
        "Rewa",
        "Sagar",
        "Satna",
        "Shehore",
        "Seoni",
        "Shahdol",
        "Shajapur",
        "Sheopur",
        "Shivpuri",
        "Sidhi",
        "Singrouli",
        "Tikamgarh",
        "Ujjain",
        "Umaria",
        "Vidisha"
    ],

    "Maharashtra" =>  [
        "Ahmednagar",
        "Akola",
        "Amravati",
        "Aurangabad",
        "Need",
        "Bhandara",
        "Buldhana",
        "Chandrapur",
        "Dhule",
        "Gadchiroli",
        "Gondia",
        "Hingoli",
        "Jalgaon",
        "Jalna",
        "Kolhapur",
        "Latur",
        "Mumbai City",
        "Mumbai Suburban",
        "Nagpur",
        "Nanded",
        "Nandurbar",
        "Nashik",
        "Osmanabad",
        "Palghar",
        "Parbhani",
        "Pune",
        "Raigad",
        "Ratnagiri",
        "Sangli",
        "Satara",
        "Sindudurg",
        "Solapur",
        "Thane",
        "Wardha",
        "Washim",
        "Yavatmal"
    ],
    "Manipur" =>  [
        "Bishnupur",
        "Chandel",
        "Churachandpur",
        "Pherzawl",
        "Tengnoupal",
        "Kakching",
        "Noney",
        "Imphal East",
        "Imphal West",
        "Jiribam",
        "Kamjong",
        "Kangpokpi",
        "Senapati",
        "Tamenglong",
        "Thoubal",
        "Ukhrul"
    ],

    "Meghalaya" =>  [
        "South West Garo Hills",
        "West Garo Hills",
        "North Garo Hills",
        "East Garo Hills",
        "South Garo Hills",
        "West Khasi Hills",
        "South West Khasi Hills",
        "Eastern West Khasi Hills",
        "East Khasi Hills",
        "Ri Bhoi",
        "West Jaintia Hills",
        "East Jaintia Hills"
    ],

    "Mizoram" =>  [
        "Aizawl",
        "Lunglei",
        "Champhai",
        "Mamit",
        "Serchhip",
        "Kolasib",
        "Lawngtlai",
        "Saiha",
        "Khawzawl"
    ],

    "Nagaland" =>  [
        "Dimapur",
        "Kiphire",
        "Kohima",
        "Longleng",
        "Mokokchung",
        "Mon",
        "Paren",
        "Phek",
        "Tuensang",
        "Wokha",
        "Zunheboto",
        "Chumukedima",
        "Niuland",
        "Noklak",
        "Shamator",
        "Tseminyu"
    ],
    "Orissa" =>  [
        "Angul",
        "Balangir",
        "Baleshwar",
        "Bargarh",
        "Bhadrak",
        "Boudh",
        "Cuttack",
        "Deogarh",
        "Dhenkanal",
        "Gajapati",
        "Ganjam",
        "Jagatsinghpur",
        "Jajpur",
        "Jharsuguda",
        "Kalahandi",
        "Kandhamal",
        "Kendrapara",
        "Kendujhar",
        "Khorda",
        "Koraput",
        "Malkangiri",
        "Mayurbhanj",
        "Nabarangpur",
        "Nayagarh",
        "Nuapada",
        "Puri",
        "Rayagada",
        "Sambalpur",
        "Subarnapur",
        "Sundargarh"
    ],

    "Punjab" =>  [
        "Amritsar",
        "Barnala",
        "Bathinda",
        "Faridkot",
        "Fatehgarh Sahib",
        "Fazilka",
        "Ferozepur",
        "Gurdaspur",
        "Hoshiarpur",
        "Jalandhar",
        "Kapurthala",
        "Ludhiana",
        "Malerkotla",
        "Mansa",
        "Moga",
        "Sas Nagar",
        "Sri Muktsar Sahib",
        "SBS Nagar",
        "Pathankot",
        "Patiala",
        "Rupnagar",
        "Sangrur",
        "Tarn Taran"
    ],

    "Rajasthan" =>  [
        "Ajmer",
        "Alwar",
        "Banswara",
        "Baran",
        "Barmer",
        "Bharatpur",
        "Bhilwara",
        "Bikaner",
        "Bundi",
        "Chittorgarh",
        "Churu",
        "Dausa",
        "Dholpur",
        "Dungarpur",
        "Hanumangarh",
        "Jaisalmer",
        "Jaipur",
        "Jalor",
        "Jhalawar",
        "Jhunjhunu",
        "Jodhpur",
        "Karauli",
        "Kota",
        "Nagaur",
        "Pali",
        "Pratapgarh",
        "Rajsamand",
        "Sawai Madhopur",
        "Sikar",
        "Sirohi",
        "Sri Ganganagar",
        "Tonk",
        "Udaipur"
    ],
    "Sikkim" =>  [
        "Gangtok",
        "Mangan",
        "Gyalshing",
        "Namchi",
        "Pakyong",
        "Soreng"
    ],

    "Tamil Nadu" =>  [
        "Ariyalur",
        "Chengalpattu",
        "Chennai",
        "Coimbatore",
        "Cuddalore",
        "Dharmapuri",
        "Dindigul",
        "Erode",
        "Kallakurichi",
        "Kancheepuram",
        "Kanniyakumari",
        "Karur",
        "Krishnagiri",
        "Madurai",
        "Mayiladuthurai",
        "Nagapattinam",
        "Namakkal",
        "Nilgiris",
        "Perambalur",
        "Pudukkottai",
        "Ramanathapuram",
        "Ranipet",
        "Salem",
        "Sivaganga",
        "Tenkasi",
        "Thanjavur",
        "Theni",
        "Thoothukudi",
        "Tiruchirapalli",
        "Tirunelveli",
        "Tirupathur",
        "Tiruvannamalai",
        "Tiruvarur",
        "Vellore",
        "Viluppuram",
        "Virudhunagar"
    ],

    "Telangana" =>  [
        "Adilabad",
        "Hyderabad",
        "Jagtial",
        "Jangaon",
        "Jayashankar Bhupalapally",
        "Jogulamba Gadwal",
        "Kamareddy",
        "Karimnagar",
        "Khammam",
        "Bhadradri Kothagudem",
        "Komaram Bheem Asifabad",
        "Mahabubnagar",
        "Mahabubabad",
        "Mancherial",
        "Medak",
        "Medchal Malkajgiri",
        "Mulugu",
        "Nagarkurnool",
        "Nalgonda",
        "Narayanpet",
        "Nirmal",
        "Nizamabad",
        "Pedapalli",
        "Rajanna Sircilla",
        "Rangareddy",
        "Sangareddy",
        "Siddipet",
        "Suryapet",
        "Vikarabad",
        "Wanaparthy",
        "Hanumakonda",
        "Warangal",
        "Yadadri Bhuvanagari"
    ],

    "Tripura" =>  [
        "Dhalai",
        "Gomati",
        "Khowai",
        "North Tripura",
        "Sepahijala",
        "South Tripura",
        "Unakoti",
        "West Tripura"
    ],
    "Uttar Pradesh" =>  [
        "Agra",
        "Aligarh",
        "Allahabad",
        "Ambedkar Nagar",
        "Auraiya",
        "Azamgarh",
        "Bagpat",
        "Bahraich",
        "Ballia",
        "Balrampur",
        "Banda",
        "Barabanki",
        "Bareilly",
        "Basti",
        "Bijnor",
        "Budaun",
        "Bulandshahr",
        "Chandauli",
        "Chitrakoot",
        "Deoria",
        "Etah",
        "Etawah",
        "Faizabad",
        "Farrukhabad",
        "Fatehpur",
        "Firozabad",
        "Gautam Buddha Nagar",
        "Ghaziabad",
        "Ghazipur",
        "Gonda",
        "Gorakhpur",
        "Hamirpur",
        "Hardoi",
        "Hathras",
        "Jalaun",
        "Jaunpur",
        "Jhansi",
        "Jyotiba Phule Nagar",
        "Kannauj",
        "Kanpur Dehat",
        "Kanpur Nagar",
        "Kaushambi",
        "Kheri",
        "Kushinagar",
        "Lalitpur",
        "Lucknow",
        "Mahoba",
        "Maharajganj",
        "Mainpuri",
        "Mathura",
        "Mau",
        "Meerut",
        "Mirzapur",
        "Moradabad",
        "Muzaffarnagar",
        "Pilibhit",
        "Pratapgarh",
        "RaeBareli",
        "Rampur",
        "Saharanpur",
        "Sant Kabir Nagar",
        "Sant Ravidas Nagar",
        "Shahjahanpur",
        "Shravasti",
        "Siddharthnagar",
        "Sitapur",
        "Sonbhadra",
        "Sultanpur",
        "Unnao",
        "Varanasi",
        "Manyavar Kanshiram Nagar",
        "Prabuddha Nagar",
        "Panchsheel Nagar",
        "Bhim Nagar",
        "Chhatrapati Shahuji Maharaj Nagar"
    ],
    "Uttarakhand" =>  [
        "Almora",
        "Bageshwar",
        "Chamoli",
        "Champawat",
        "Dehradun",
        "Haridwar",
        "Nainital",
        "Pauri Garhwal",
        "Pithoragarh",
        "Rudraprayag",
        "Tehri Garhwal",
        "Udham Singh Nagar",
        "Uttarkashi"
    ],

    "West Bengal" =>  [
        "North 24 Parganas",
        "South 24 Parganas",
        "Bankura",
        "Birbhum",
        "Cooch Behar",
        "Dakshin Dinajpur",
        "Darjeeling",
        "Hooghly",
        "Howrah",
        "Jalpaiguri",
        "Jhargram",
        "Kalimpong",
        "Kolkata",
        "Malda",
        "Murshidabad",
        "Nadia",
        "Paschim Burdwan",
        "Purba Burdwan",
        "Paschim Medinipur",
        "Purba Medinipur",
        "Purulia",
        "Uttar Dinajpur",
        "Alipurduar"
    ],

    "Delhi" =>  [
        "Central Delhi",
        "North Delhi",
        "South Delhi",
        "East Delhi",
        "North East Delhi",
        "South West Delhi",
        "New Delhi",
        "North West Delhi",
        "West Delhi",
        "Shahdara",
        "South East Delhi"
    ],

    "Andaman and Nicobar Islands" =>  ["Nicobar", "North and Middle Andaman", "South Andaman"],

    "Chandigarh" =>  ["Chandigarh"],

    "Dadra and Nagar Haveli and Daman and Diu" =>  ["Dadra and Nagar Haveli", "Daman", "Diu"],

    "Jammu and Kashmir" =>  [
        "Anantnag",
        "Bandipora",
        "Baramulla",
        "Budgam",
        "Doda",
        "Ganderbal",
        "Jammu",
        "Kathua",
        "Kishtwar",
        "Kulgam",
        "Kupwara",
        "Poonch",
        "Pulwama",
        "Rajouri",
        "Ramban",
        "Reasi",
        "Samba",
        "Shopian",
        "Srinagar",
        "Udhampur"
    ],
    "Ladakh" =>  ["Kargil", "Leh"],

    "Lakshadweep" =>  [
        "Agatti",
        "Amini",
        "Andrott",
        "Bitra",
        "Chetlat",
        "Kadmat",
        "Kalpeni",
        "Kavaratti",
        "Kiltan",
        "Minicoy"
    ],

    "Puducherry" =>  ["Karaikal", "Mahe", "Puducherry", "Yanam"]


];

header('Content-Type: application/json');

if (isset($_POST['state'])) {
    $state = $_POST['state'];
    $districts = $stateDistricts[$state] ?? [];
    echo json_encode($districts);
} else {
    echo json_encode([]);
}

?>